version: '3.8'

services:
  dotnet_postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: homework_database
    ports:
      - 5432:5432
    volumes:
      - dotnet_postgres_data:/var/lib/postgresql/data
    
  #dotnet_rabbitmq:
  #  image: rabbitmq:3-alpine
    
  #dotnet_minio:
  #  image: minio/minio:latest
    
  #dotnet_mongodb:
  #  image: mongo:latest
    
  #dotnet_jaeger:
  #  image: jaegertracing/all-in-one:latest
    
  dotnet_main:
    image: dotnet-web
    build:
      context: .
      dockerfile: Dotnet.Homeworks.MainProject/Dockerfile
    ports:
      - 5065:8080
    depends_on:
      - dotnet_postgres
    environment:
      ConnectionStrings__Default: Host=db;Username=postgres;Password=postgres;Database=homework_database
    
    
  #dotnet_mailing:
  #  image: dotnet-web
    
  #dotnet_storage:
  #  image: dotnet-web

volumes:
  dotnet_postgres_data: